# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu2004"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.20", virtualbox__intnet: "epcnet", name: "epcnet"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  config.vm.provider "virtualbox" do |vb|
	vb.memory = 4096
	vb.cpus = 8
	vb.default_nic_type = "virtio"
	vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all", "--nicpromisc2", "allow-all"]
  end

  config.vm.provision "file", source: "provision_files/", destination: "/tmp/"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
	sudo apt update -y
	sudo apt install -y bzip2 net-tools bridge-utils libsctp-dev python3 python3-setuptools python3-wheel git libgnutls28-dev libgcrypt20-dev libssl-dev libidn11-dev libmongoc-dev libbson-dev libyaml-dev libnghttp2-dev libmicrohttpd-dev libcurl4-gnutls-dev libnghttp2-dev libtins-dev libfftw3-dev libmbedtls-dev libconfig++-dev libczmq-dev libfftw3-dev libmbedtls-dev libconfig++-dev libsctp-dev libboost-program-options1.71.0 jq
	#
	sudo mkdir -p /opt/LTE/
	chown vagrant /opt/LTE
	#
	if [ -f /tmp/provision_files/precompiled/lte-ran-precompiled.tar.bz2 ] ; then
		echo "Using precompiled binaries"
		cd /opt/
		tar -xvvpjf /tmp/provision_files/precompiled/lte-ran-precompiled.tar.bz2
	else
		echo "Will compile from scratch"
		sudo snap install cmake --classic
		sudo apt install -y gcc make g++ ninja-build build-essential flex bison meson libboost-program-options-dev python3-pip
		git clone https://github.com/aligungr/UERANSIM.git
		cd UERANSIM
		git checkout v3.2.3
		make
		mkdir -p /opt/LTE/ueransim/etc
		mkdir -p /opt/LTE/ueransim/bin
		mv build/* /opt/LTE/ueransim/bin/
		cd ..
		#
		git clone https://github.com/srsRAN/srsRAN.git
		cd srsRAN
		git checkout release_21_04
		mkdir build
		cd build
		cmake -DCMAKE_INSTALL_PREFIX=/opt/LTE/srsRAN ../
		make
		sudo make install
		cd /opt/
		tar -cvvpjf lte-ran-precompiled.tar.bz2 LTE/ueransim LTE/srsRAN
	fi
	echo "/opt/LTE/srsRAN/lib/" >> /etc/ld.so.conf
	ldconfig
	sudo cp -arv /tmp/provision_files/LTE/* /opt/LTE/
	reboot
  SHELL
end
